# Generated by Django 3.2.7 on 2021-12-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='D:\\My works\\Code Playground\\PROJECTS\\Recipe Book\\recipe_book_backend\\media\\users\\images\\default.png', upload_to='users/images'),
        ),
    ]
