# Generated by Django 3.2.7 on 2022-01-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='D:\\My works\\Code Playground\\PROJECTS\\Recipe Book\\recipe_book_backend\\media\\users\\images\\default.png', max_length=1000, upload_to='users/images'),
        ),
    ]
