# Generated by Django 4.0.5 on 2022-06-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220131_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='D:\\My works\\Code Playground\\DEPLOYMENT_PROJECTS\\Recipe Book\\recipe_book_backend\\media\\users\\images\\default.png', max_length=1000, upload_to='users/images'),
        ),
    ]
