# Generated by Django 3.2.7 on 2021-12-13 03:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('recipe_image', models.ImageField(default='D:\\My works\\Code Playground\\PROJECTS\\Recipe Book\\recipe_book_backend\\media\\recipes\\images\\default.png', upload_to='recipes/images')),
                ('materials_required', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, size=None)),
                ('procedure', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200), blank=True, size=None)),
                ('precautions', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
