# Generated by Django 3.2.7 on 2021-12-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='procedure',
        ),
    ]
