# Generated by Django 3.2.7 on 2021-12-13 05:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='procedure',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default='', max_length=200), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='materials_required',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
