# Generated by Django 3.2.7 on 2021-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_precautions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='D:\\My works\\Code Playground\\PROJECTS\\Recipe Book\\recipe_book_backend\\media\\recipes\\images\\default.png', max_length=1000, upload_to='recipes/images'),
        ),
    ]
