# Generated by Django 3.2.7 on 2021-12-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_recipe_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='materials_required',
            new_name='mats_req',
        ),
    ]
