# Generated by Django 3.2.7 on 2021-12-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20211218_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
