# Generated by Django 3.2.7 on 2021-12-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='type',
        ),
    ]
