# Generated by Django 3.2.7 on 2021-12-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='mats_req',
            new_name='ingredients_req',
        ),
    ]
