# Generated by Django 3.2.7 on 2022-01-31 15:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 1, 31, 15, 22, 1, 126996, tzinfo=utc)),
        ),
    ]
