# Generated by Django 3.2.7 on 2022-02-02 12:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 2, 2, 12, 52, 0, 994231, tzinfo=utc)),
        ),
    ]
