# Generated by Django 3.2.7 on 2022-02-04 04:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20220202_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2022, 2, 4, 4, 26, 10, 527962, tzinfo=utc)),
        ),
    ]
