# Generated by Django 4.0.5 on 2022-06-22 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_alter_recipe_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created_by',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='date_created',
            field=models.DateField(default=datetime.date(2022, 6, 22)),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(default='recipes\\images\\default.png', max_length=1000, upload_to='recipes/images'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
